jasypt:
  encryptor:
    password: 123456

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college_salary_management?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: ENC(1WR/22mbNNOuN63wUsLqzg==)
    password: ENC(ecVcBioVCBu7SP8bgj5U8Q==)
    driver-class-name: com.mysql.jdbc.Driver
#   main.banner-mode: off  springboot 图标
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

# 关闭 springboot 默认日志输出
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
      root: off

# 分页需要
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true




